### ISSUE TITLE
Chest++ not working on spigot or paper servers. Tested with no additional plugins and near default spigot.yml. 1.16.1

### ISSUE THREAD

**Issue by AndroidDev01** [JamesPeters98/ChestsPlusPlus#15]
Error logs enclosed.

[13:22:36 INFO]: [ChestsPlusPlus] Enabling ChestsPlusPlus v2.2.1-Release
[13:22:36 INFO]: [ChestsPlusPlus] Found API version: v1_16_R1
[13:22:36 INFO]: [ChestsPlusPlus] Chests++ enabled!
[13:22:36 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:22:36 INFO]: Done (5.143s)! For help, type "help"
[13:22:39 WARN]: [ChestsPlusPlus] Task #3 for ChestsPlusPlus v2.2.1-Release generated an exception
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:32) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:1) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:31) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:1) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at com.jamesdpeters.minecraft.chests.crafting.Crafting.load(Crafting.java:27) ~[?:?]
	at com.jamesdpeters.minecraft.chests.ChestsPlusPlus.lambda$onEnable$1(ChestsPlusPlus.java:142) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[13:22:40 INFO]: [ChestsPlusPlus] Plugin is up to date! Thank you for supporting Chests++!

And

org.bukkit.command.CommandException: Unhandled exception executing command 'cl' in plugin ChestsPlusPlus v2.2.1-Release
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
	at com.jamesdpeters.minecraft.chests.commands.ChestLinkCommand.onCommand(ChestLinkCommand.java:107) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
	... 18 more

No part of chest++ functions.

**Comment by AndroidDev01** [comment]
Just did some troubleshooting and it your plugin runs fine with a new worldfile.  Not sure why but my world was causing issues.

**Comment by JamesPeters98** [comment]
Do you use any plugins that add custom recipes at all? It seems like an autocraft recipe was added to the system with no output item. So either your config was corrupted or there was a bug with the autocrafting. Either way, I'll add a check for it so that it doesn't cause a crash 👍
