### ISSUE TITLE
Critical Server Error by Chest++ 2.4.1

### ISSUE THREAD

**Issue by jaminsmoke** [JamesPeters98/ChestsPlusPlus#39]
Hi. At first say that i love this plugin jeje. but in 2.4.1 version seem havent problems at first days but with server activity and use the plugin, Chest++ send this bug repeteadly.

[13:29:18 WARN]: AsyncLogger error handling event seq=7876, value='':
[13:29:18 WARN]: java.lang.NullPointerException
[13:29:18 ERROR]: Could not pass event InventoryMoveItemEvent to ChestsPlusPlus v2.4.1-Release
java.lang.ArrayIndexOutOfBoundsException: null

That its the 'main' lines i think but send a thousand of lines like a cyclic and puto something like overflow but i dont understando so much of this... sorry and thanks for do so great work.  have to delete the plugin. if can fix i will put again without a doubt. but my server console its freeze with this bug

**Comment by jaminsmoke** [comment]
Now i can see that a player in my server put incoherent itemframes and chestlink chest in a item filter system building. This is a player error of course, but the effect of this is the break of the server in a cyclic error mesagges. Sorry for my bad english and my bad java comprension.

**Comment by JamesPeters98** [comment]
Hey, would you mind posting a video or photos of what you mean? :)

**Comment by JamesPeters98** [comment]
I'd like to fix this issue so if you could provide more info on how to replicate it that'd be helpful.

**Comment by jaminsmoke** [comment]
Yes sorry for late so much this is the complete error i think.

at com.jamesdpeters.minecraft.chests.listeners.HopperListener.onHopperMoveEvent(HopperListener.java:55) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1534.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-564]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-564]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-564]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-564]
        
        It produces when you put a same type of chestlink and 2 or mor with hopper and one out of systrem of hoppers. So when have to put item in a chest hace more than one that it is getting items, so the plugin triguer this error in cyclic while hopper event its active because more than 1 hopper are actuating at time in only 1 type (category: ej. minechest). Sorry for my english if u need a video to see better this i can do it. sorry and thanks for this great plugin

**Comment by stefanws0** [comment]
Just letting you know I am also having issues regarding this error, except I don't entirely know if it is from the same cause.
