### ISSUE TITLE
java.lang.RuntimeException: Currently no NMS version support for v1_17_R1

### ISSUE THREAD

**Issue by ErythroCraft** [JamesPeters98/ChestsPlusPlus#52]
[19:33:11] [Server thread/WARN]: [ChestsPlusPlus] You may be running an outdated version of the plugin or it needs to be updated to the latest version!
[19:33:11] [Server thread/ERROR]: Error occurred while enabling ChestsPlusPlus v2.4.1-Release (Is it up to date?)
java.lang.RuntimeException: Currently no NMS version support for v1_17_R1
        at com.jamesdpeters.minecraft.chests.Api.setupNMSProvider(Api.java:30) ~[?:?]
        at com.jamesdpeters.minecraft.chests.api.ApiSpecific.init(ApiSpecific.java:17) ~[?:?]
        at com.jamesdpeters.minecraft.chests.ChestsPlusPlus.onEnable(ChestsPlusPlus.java:100) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:dev-Spigot-101ebb6-9122f5a]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by ErythroCraft** [comment]
Close this request for waiting too long.
I updated the plugin myself.

**Comment by SaajidDE** [comment]
@ErythroCraft would you mind sharing your work? I also contacted you on facebook regarding the same thing.
You can also get in touch via discord if you're willing to share. Saajid#0001

**Comment by ErythroCraft** [comment]
@SaajidDE 
Sorry, but this is not allowed. I created by self. (It's an simple compile with JDK 16)
I can not do the work of @JamesPeters98 and I'll delete my forke after update.
sry
