### ISSUE TITLE
Unable to add items to a chestlink through a hopper

### ISSUE THREAD

**Issue by Gamebreaker259** [JamesPeters98/ChestsPlusPlus#56]
First like to say that I LOVE this plug-in and have used it for years on my private server. I just recently upgraded to 1.17.1 and started using the beta 2.5 version. I am also using Paper version 1.17.1 #251.

I am now not able to add items to a chestlink through a hopper. If you create a chest and add a chestlink to it, place a hopper into that chest. Then place another chest over that hopper. Place some items in the chest above. The items will get pulled out of the top chest but won't be added to the chestlink chest and just get lost somewhere.
![2021-09-06_16 12 58](https://user-images.githubusercontent.com/74880323/132260849-44f9d5e7-8b93-406c-bb98-22da7cbd1d25.png)

I have also tried it without the chestlink on the bottom chest and the items get pulled out of the top chest and deposited in the bottom chest.
![2021-09-06_16 13 09](https://user-images.githubusercontent.com/74880323/132260855-bdcc4e43-2366-45a8-9f32-cd909f89dc0d.png)

**Comment by WalnutWhip** [comment]
also have this problem on ChestsPlusPlus-2.5-Release.jar

**Comment by JamesPeters98** [comment]
Seems like this may be caused by another plugin, if you can isolate the problem in a test server and send over the server files that would be great.

I'd start by removing other plugins 1 by 1 until the problem stops.

And provide any logs that may show why this is happening.

**Comment by Gamebreaker259** [comment]
I updated my server to the latest release and have removed all other plug-ins and started the server. Started Minecraft and logged into server. Added a chest link to the bottom chest. Dropped an item into the top chest. Checked bottom chest and no item. If I then remove the chestlink, then I get my items back. Seems like the items are dropping into the regular chest, not the chestlink. Then if I remove the chestlink, I get the following error:

[09:43:25 INFO]: drdan512 issued server command: /cl remove test
[09:43:25 WARN]: [ChestsPlusPlus] Plugin ChestsPlusPlus v2.5.1-Release generated an exception while executing task 16
java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.17.1.jar:git-Paper-400]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:41) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:275) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243) ~[patched_1.17.1.jar:git-Paper-400]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:220) ~[patched_1.17.1.jar:git-Paper-400]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:41) ~[patched_1.17.1.jar:git-Paper-400]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.17.1.jar:git-Paper-400]
        at com.jamesdpeters.minecraft.chests.serialize.Config.save(Config.java:67) ~[ChestsPlusPlus-2.5.1-Release.jar:?]        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-400]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-400]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-400]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by JamesPeters98** [comment]
If you could ZIP up your server files for me so I can test it myself, including the Spigot/Paper jar you are using and the plugins too.

That way I can replicate what's happening exactly
