### ISSUE TITLE
Nullpointer when opening public chestlink via /chestlink open

### ISSUE THREAD

**Issue by yuri0r** [JamesPeters98/ChestsPlusPlus#6]
Basicly the title. using chest++ v1.3.
but only when someone other than the creator tries to acces the chest vio command

**Comment by JamesPeters98** [comment]
Hey! Can you post the log from the crash, along with the chests.yml file from the root directory of your server please :)

**Comment by yuri0r** [comment]
chests.yml
[chests.yml.txt](https://github.com/JamesPeters98/ChestsPlusPlus/files/4536160/chests.yml.txt)

log
[latest.log](https://github.com/JamesPeters98/ChestsPlusPlus/files/4536168/latest.log)


`[20:07:07] [Server thread/INFO]: yuri0r issued server command: /cl open trading2
[20:07:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cl' in plugin ChestsPlusPlus v1.15 v1.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-213]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-213]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1076) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1069) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1033) ~[patched_1.15.2.jar:git-Paper-213]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-213]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at com.jamesdpeters.minecraft.chests.commands.RemoteChestCommand.onCommand(RemoteChestCommand.java:94) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-213]
	... 17 more`

**Comment by JamesPeters98** [comment]
Hey could you provide me with a screenshot of what happens when you enter /cl menu

**Comment by JamesPeters98** [comment]
And the name of the chests that show up in it

**Comment by JamesPeters98** [comment]
I have a feeling the person running that command isn't the owner of the chest. And currently, only the owner can open the chest, the next version will allow you to open other people's chests though! :)

**Comment by JamesPeters98** [comment]
> but only when someone other than the creator tries to acces the chest vio command
Ah yes I just noticed this, that is why it's not working.

**Comment by JamesPeters98** [comment]
This is fixed in the latest update and will be out on the plugin page in the next day or two.
