### ISSUE TITLE
Nullpointer when using /cl add

### ISSUE THREAD

**Issue by Jackal96** [JamesPeters98/ChestsPlusPlus#66]
Running on Paper version git-Paper-140 (MC: 1.18.1)

Error happens both with this beta and the current release. Every time I add a chest using the command. Let me know if I can provide any more information :)

[17:43:56 WARN]: Plugin ChestsPlusPlus v2.5.2-BETA-4 generated an exception while executing task 410
java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:41) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:41) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.toNodeTree(YamlConfiguration.java:186) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:77) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.jamesdpeters.minecraft.chests.serialize.Config.save(Config.java:67) ~[ChestsPlusPlus-2.5.2-BETA-4.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-140]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-140]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-140]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LilianLem** [comment]
Same here on Paper 1.18.1 version 175. The same error is also displayed when a non-member player of the ChestLink destroys the sign on the chest, even if he's not allowed todo so.
