### ISSUE TITLE
Error to do with item moving and hoppers

### ISSUE THREAD

**Issue by cfitz25** [JamesPeters98/ChestsPlusPlus#68]
Hello, my server is getting spammed by this plugin. Once with the top bit and the last bit gets repeated many times a second.
Ive tried it on both of the latest versions of purpur and papermc, i think it may have started happening after i put an itemframe on a hopper for filtering.
May have to do with it trying to pull from the frame maybe.
```INFO [ChestsPlusPlus] Plugin is up to date! Thank you for supporting Chests++!
23.01 20:56:35 [Server] ERROR Could not pass event InventoryMoveItemEvent to ChestsPlusPlus v2.5.1-Release
23.01 20:56:35 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
23.01 20:56:35 [Server] INFO at java.util.Arrays$ArrayList.get(Arrays.java:4164) ~[?:?]
23.01 20:56:35 [Server] INFO at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:35 [Server] INFO at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.getItem(RandomizableContainerBlockEntity.java:111) ~[?:?]
23.01 20:56:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:35 [Server] INFO at com.jamesdpeters.minecraft.chests.listeners.HopperListener.onHopperMoveEvent(HopperListener.java:56) ~[ChestsPlusPlus-2.5.1-Release.jar:?]
23.01 20:56:35 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor13.execute(Unknown Source) ~[?:?]
23.01 20:56:35 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.01 20:56:35 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1442]
23.01 20:56:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.01 20:56:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.01 20:56:35 [Server] INFO at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.01 20:56:35 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.callPullMoveEvent(HopperBlockEntity.java:308) ~[?:?]
23.01 20:56:35 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPull(HopperBlockEntity.java:248) ~[?:?]
23.01 20:56:35 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.lambda$suckInItems$3(HopperBlockEntity.java:461) ~[?:?]
23.01 20:56:35 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.anyMatch(HopperBlockEntity.java:439) ~[?:?]
23.01 20:56:35 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.suckInItems(HopperBlockEntity.java:458) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.lambda$pushItemsTick$0(HopperBlockEntity.java:141) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:163) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:140) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1167) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1119) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1003) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:704) ~[?:?]
23.01 20:56:36 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1632) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:36 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:36 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:36 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1442]
23.01 20:56:36 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.01 20:56:36 [Server] ERROR Could not pass event InventoryMoveItemEvent to ChestsPlusPlus v2.5.1-Release
23.01 20:56:36 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: null```

**Comment by cfitz25** [comment]
Sorry seems to not be to do with itemframes

**Comment by JamesPeters98** [comment]
Try the latest beta and it should be fixed: https://github.com/JamesPeters98/ChestsPlusPlus/releases/tag/v2.5.2-BETA-5
