### ISSUE TITLE
hopper transfer amount always 1

### ISSUE THREAD

**Issue by proy27** [JamesPeters98/ChestsPlusPlus#8]
i change "hopper-amount" to 10
hopper transfer things to chestlink, all is one by one
but normal chest is 10

**Comment by JamesPeters98** [comment]
Hey, you also have to change the hopper-amount in the main spigot file for normal chests to be affected! If you're using Bukkit then this isn't possible!

**Comment by proy27** [comment]
i use PaperMC
i only change "spigot.yml"  "hopper-amount:"

normal chest > chestlink chest X1
chestlink chest > chestlink chest X1
chestlink chest > normal chest X1
normal chest > normal chest X10

The setting doesn't work on chestlink chest

**Comment by JamesPeters98** [comment]
Hey, what version of PaperMC are you using and what version of the plugin?

I have just tested on Paper366 with the latest plugin version 1.4 and everything is working as intended, using the following in spigot.yml:

```
world-settings:
  default:
    hopper-amount: 10
```

**Comment by proy27** [comment]
ChestsPlusPlus-1.15+v1.4.jar
paper-366.jar

> [20:54:24] [Server thread/INFO]: Starting minecraft server version 1.15.2
[20:54:24] [Server thread/INFO]: Loading properties
[20:54:24] [Server thread/INFO]: This server is running Paper version git-Paper-366 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[20:54:24] [Server thread/INFO]: Debug logging is disabled
[20:54:24] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:54:24] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:54:24] [Server thread/INFO]: Default game type: SURVIVAL
[20:54:24] [Server thread/INFO]: Generating keypair
[20:54:24] [Server thread/INFO]: Starting Minecraft server on *:58811
[20:54:24] [Server thread/INFO]: Using default channel type
[20:54:26] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[20:54:29] [Server thread/WARN]: Legacy plugin WarnedAutoSave v1.0-SNAPSHOT does not specify an api-version.
[20:54:29] [Server thread/WARN]: Legacy plugin MiaoBoard v2.5.0-git-fdf05fc1c0c21b8fb30cf99ccb58d20e396ebfc7 does not specify an api-version.
[20:54:29] [Server thread/WARN]: Legacy plugin LuckPermsGUI v3.5 does not specify an api-version.
[20:54:29] [Server thread/WARN]: Legacy plugin dynmap v3.0-RC3-331 does not specify an api-version.
[20:54:29] [Server thread/INFO]: [AdvancedPortals] Loading AdvancedPortals v0.5.2
[20:54:29] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v4.4.1
[20:54:29] [Server thread/INFO]: [ChopTree2] Loading ChopTree2 v1.14.2-2.4.3
[20:54:29] [Server thread/INFO]: [WarnedAutoSave] Loading WarnedAutoSave v1.0-SNAPSHOT
[20:54:29] [Server thread/INFO]: [StackMob] Loading StackMob v5.1.2
[20:54:29] [Server thread/INFO]: [Minepacks] Loading Minepacks v2.3.8-Release
[20:54:29] [Server thread/INFO]: [Minepacks] PCGF-PluginLib not installed. Switching to standalone mode!
[20:54:29] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.4
[20:54:29] [Server thread/INFO]: [VillagerOptimiser] Loading VillagerOptimiser v1.1.2
[20:54:29] [Server thread/INFO]: [MiaoBoard] Loading MiaoBoard v2.5.0-git-fdf05fc1c0c21b8fb30cf99ccb58d20e396ebfc7
[20:54:29] [Server thread/INFO]: [ChestsPlusPlus] Loading ChestsPlusPlus v1.15 v1.4
[20:54:29] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[20:54:29] [Server thread/INFO]: [LuckPermsGUI] Loading LuckPermsGUI v3.5
[20:54:29] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.0
[20:54:29] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.15.2) has not yet been tested! Proceed with caution.
[20:54:30] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-RC3-331
[20:54:30] [Server thread/INFO]: [dynmap] version=git-Paper-366 (MC: 1.15.2)
[20:54:30] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[20:54:30] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[20:54:30] [Server thread/INFO]: [dynmap] Mod Support API available
[20:54:30] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.1.1-SNAPSHOT+4866-28c3dd4
[20:54:31] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@2cc5c7d4]
[20:54:31] [Server thread/INFO]: [MiaoChat] Loading MiaoChat v1.9.1-git-05219d509c68b48b3b6508dd57b3c69dba1535ea
[20:54:31] [Server thread/INFO]: [Essentials] Loading Essentials v2.17.1.60
[20:54:31] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect v2.17.1.60
[20:54:31] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.17.1.60
[20:54:31] [Server thread/INFO]: [RepairGui] Loading RepairGui v6.5.2
[20:54:31] [Server thread/INFO]: [EnchantGui] Loading EnchantGui v3.1.4
[20:54:31] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.17.1.60
[20:54:31] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:54:31] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.4.1
[20:54:31] [Server thread/INFO]:         __    
[20:54:31] [Server thread/INFO]:   |    |__)   LuckPerms v4.4.1
[20:54:31] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[20:54:31] [Server thread/INFO]: 
[20:54:31] [Server thread/INFO]: [LuckPerms] Loading configuration...
[20:54:31] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[20:54:31] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[20:54:31] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[20:54:31] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 851ms)
[20:54:31] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[20:54:31] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.17.1.60 which is not a depend, softdepend or loadbefore of this plugin.
[20:54:31] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[20:54:32] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[20:54:32] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[20:54:32] [Server thread/WARN]: [LuckPerms] Loaded class net.milkbowl.vault.permission.Permission from Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} which is not a depend, softdepend or loadbefore of this plugin.
[20:54:32] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[20:54:32] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.0
[20:54:32] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[20:54:32] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.1.1-SNAPSHOT+4866-28c3dd4
[20:54:32] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[20:54:32] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_15_R2 as the Bukkit adapter
[20:54:33] [Server thread/INFO]: Preparing level "world"
[20:54:33] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[20:54:34] [Server thread/INFO]: Loaded 6 recipes

**Comment by proy27** [comment]
i use a new paperMC server and only install ChestsPlusPlus-1.15+v1.4.jar
hopper-amount: 10
still doesn't work
```
config-version: 12
settings:
  debug: false
  sample-count: 12
  user-cache-size: 1000
  bungeecord: false
  player-shuffle: 0
  save-user-cache-on-stop-only: false
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  log-villager-deaths: true
  netty-threads: 4
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
commands:
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
  spam-exclusions:
  - /skill
  tab-complete: 0
  send-namespaced: true
  log: true
  silent-commandblock-console: false
advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    verbose: true
    view-distance: default
    arrow-despawn-rate: 1200
    trident-despawn-rate: 1200
    end-portal-sound-radius: 0
    wither-spawn-sound-radius: 0
    item-despawn-rate: 6000
    enable-zombie-pigmen-portal-spawns: true
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    nerf-spawner-mobs: false
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-outpost: 165745296
    seed-endcity: 10387313
    seed-slime: 987234911
    mob-spawn-range: 8
    hopper-amount: 10
    max-tnt-per-tick: 100
    max-entity-collisions: 8
    merge-radius:
      item: 2.5
      exp: 3.0
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100
    entity-activation-range:
      animals: 32
      monsters: 32
      raiders: 48
      misc: 16
      water: 16
      villagers: 32
      flying-monsters: 32
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      tick-inactive-villagers: true
      wake-up-inactive:
        animals-max-per-tick: 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 4
        villagers-every: 600
        villagers-for: 100
        flying-monsters-max-per-tick: 8
        flying-monsters-every: 200
        flying-monsters-for: 100
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0
    squid-spawn-range:
      min: 45.0
    max-tick-time:
      tile: 50
      entity: 50
```

**Comment by JamesPeters98** [comment]
I cannot reproduce this issue! I have tried with a clean Paper install too, so I'm not sure what's happening here!

**Comment by proy27** [comment]
can you share your logs?
```
[18:39:20] [Server thread/INFO]: Loading properties
[18:39:20] [Server thread/INFO]: This server is running Paper version git-Paper-366 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:39:20] [Server thread/INFO]: Debug logging is disabled
[18:39:20] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:39:20] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:39:20] [Server thread/INFO]: Default game type: SURVIVAL
[18:39:20] [Server thread/INFO]: Generating keypair
[18:39:20] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:39:20] [Server thread/INFO]: Using default channel type
[18:39:22] [Server thread/INFO]: [ChestsPlusPlus] Loading ChestsPlusPlus v1.15 v1.4
[18:39:22] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:39:22] [Server thread/INFO]: Preparing level "world"
[18:39:22] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[18:39:30] [Server thread/INFO]: Loaded 6 recipes
```

**Comment by proy27** [comment]
Spigot still doesn't work
```
[18:54:42] [Server thread/INFO]: Starting minecraft server version 1.15.2
[18:54:42] [Server thread/INFO]: Loading properties
[18:54:43] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a99063f-be6aaf0 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:54:43] [Server thread/INFO]: Debug logging is disabled
[18:54:43] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:54:43] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:54:43] [Server thread/INFO]: Default game type: SURVIVAL
[18:54:43] [Server thread/INFO]: Generating keypair
[18:54:43] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:54:43] [Server thread/INFO]: Using default channel type
[18:54:47] [Server thread/INFO]: [ChestsPlusPlus] Loading ChestsPlusPlus v1.15 v1.4
[18:54:47] [Server thread/INFO]: Preparing level "world"
[18:54:47] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[18:54:47] [Server thread/INFO]: Loaded 6 recipes
```

**Comment by JamesPeters98** [comment]
I feel like your spigot.yml must be incorrect/corrupted then.

Try this file:


[spigot.zip](https://github.com/JamesPeters98/ChestsPlusPlus/files/4836776/spigot.zip)

**Comment by proy27** [comment]
still doesn't work
https://drive.google.com/file/d/1kE8RL8TOYuiydeRw_DsbqKU6Nu_v5D6p/view?usp=sharing

[https://www.youtube.com/watch?v=o340Lwdsmf0](url)

**Comment by JamesPeters98** [comment]
Oh wow, sorry this has actually been fixed but I haven't pushed that update yet! I thought I had! 

Try this Beta:
https://github.com/JamesPeters98/ChestsPlusPlus/releases/tag/v1.5-Beta

**Comment by proy27** [comment]
It looks fine
but have the error
```
[21:45:10 ERROR]: Error occurred while enabling ChestsPlusPlus v1.15 v1.4.1-DEV (Is it up to date?)
java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics
	at com.jamesdpeters.minecraft.chests.ChestsPlusPlus.onEnable(ChestsPlusPlus.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: org.bstats.bukkit.Metrics
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	... 10 more
```

**Comment by JamesPeters98** [comment]
Try this:

[ChestsPlusPlus-1.15 v1.4.1-DEV.zip](https://github.com/JamesPeters98/ChestsPlusPlus/files/4837301/ChestsPlusPlus-1.15.v1.4.1-DEV.zip)

**Comment by proy27** [comment]
to late 
i lost all data=.=

**Comment by JamesPeters98** [comment]
Just restore the chests.yml from the ZIP file you sent me?

**Comment by proy27** [comment]
that is test server 
i forget backup...

**Comment by JamesPeters98** [comment]
Ah man, I thought you were still using your test server otherwise I would have recommended you wait until a stable version is out! :(
